### ISSUE TITLE
Jupyter notebook cell border not visible

### ISSUE THREAD

**Issue by echomehran** [uloco/theme-bluloco-dark#12] opened 2021-04-04 08:39 UTC
I use the theme and I think the color harmony is very good but in jupyter notebook extension cells are not bordered or focused and it makes my eyes tired in long-term work I've tweaked the `workbench.colorCustomizations` but it didn't work

**Comment by uloco** [comment] 2021-04-04 09:06
Could you please provide an example notebook file and maybe a screenshot? I already looked into notebooks and fixed everything I noticed, but some parts weren't implemented yet. Also don't use them myself, so not sure exactly what you mean.

**Comment by echomehran** [comment] 2021-04-04 10:18
![Screenshot 2021-04-04 134637](https://user-images.githubusercontent.com/70349967/113505522-971d3f80-9554-11eb-9667-a0abde8f650b.png)
 
I mean the part between input and output I want to have them separated by different colors or border like this one

![2](https://user-images.githubusercontent.com/70349967/113505603-26c2ee00-9555-11eb-81c2-4e65a11dd7a2.png)

**Comment by echomehran** [comment] 2021-04-09 09:48
the white edition is like what I want; I think the problem is with color


![Screenshot 2021-04-09 141155](https://user-images.githubusercontent.com/70349967/114161931-d6290780-993d-11eb-9200-0aa3cd92f805.png)

**Comment by uloco** [comment] 2021-04-12 09:51
Thanks for clearing this up, will look into it when I got time this week.

**Comment by uloco** [comment] 2021-04-20 10:10
Do you have the latest version of the theme? Because when I try to replicate I got this:

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/8818340/115379000-68989900-a1d1-11eb-99f6-bd74696898bd.png">

Also make sure you use the latest vscode version please.

**Comment by uloco** [comment] 2021-04-20 10:29
Maybe this ticket is also helpful: https://github.com/microsoft/vscode-jupyter/issues/580

**Comment by echomehran** [comment] 2021-04-20 11:30
> Do you have the latest version of the theme? Because when I try to replicate I got this:
> 
> <img alt="image" width="1227" src="https://user-images.githubusercontent.com/8818340/115379000-68989900-a1d1-11eb-99f6-bd74696898bd.png">
> 
> Also make sure you use the latest vscode version please.

 I have the latest version of both of them
 vscode is the latest version >>>1.55.2 
 And my theme version is v3.3.4 
 
 Also in other themes that I've sent above it's ok

**Comment by echomehran** [comment] 2021-04-20 11:52
> Maybe this ticket is also helpful: [microsoft/vscode-jupyter#580](https://github.com/microsoft/vscode-jupyter/issues/580)

I think it doesn't have to do with my problem because in this case if I'm not mistaken I should use the insider version of vscode but I use the stable version. In addition, the white edition of your theme is ok as I mentioned above

**Comment by uloco** [comment] 2021-04-20 13:15
I am also using the stable version and seeing a different UI (the new one). Your screenshots show an old UI. I did update the theme according to the new colors, so it might be different for light and dark of course.

I cannot reproduce the issue on my side because the UI is different. The ticket above describes an issue with the jupyter notebook UI not updating (since vscode changed it a few updates ago), which was in insiders back then but is now default in stable. Maybe you have a setting to use the old UI in your user settings?

**Comment by uloco** [comment] 2021-04-20 13:19
Are you using the deprecated jupyter extension maybe?
<img width="402" alt="image" src="https://user-images.githubusercontent.com/8818340/115402553-cc2fc000-a1eb-11eb-95ad-5b1f8d658180.png">

**Comment by echomehran** [comment] 2021-04-20 13:25
> Are you using the deprecated jupyter extension maybe?
> <img alt="image" width="402" src="https://user-images.githubusercontent.com/8818340/115402553-cc2fc000-a1eb-11eb-95ad-5b1f8d658180.png">

No, I'm using the first one

**Comment by uloco** [comment] 2021-04-20 13:30
Oh I think now I understand what the problem is. It's in interactive mode. Will look into it!

**Comment by echomehran** [comment] 2021-04-20 13:35
> Oh I think now I understand what the problem is. It's in interactive mode. Will look into it!

I don't think so, take a look at this it's the interactive mode

![Screenshot 2021-04-20 180335](https://user-images.githubusercontent.com/70349967/115404752-de692880-a202-11eb-8a1a-46d8f989b9e6.png)

**Comment by uloco** [comment] 2021-04-20 13:35
Have you overwritten some styles in your settings.json? I seriously cannot understand what is going on

**Comment by echomehran** [comment] 2021-04-20 13:36
> > Are you using the deprecated jupyter extension maybe?
> > <img alt="image" width="402" src="https://user-images.githubusercontent.com/8818340/115402553-cc2fc000-a1eb-11eb-95ad-5b1f8d658180.png">
> 
> No, I'm using the first one

![Screenshot 2021-04-20 180039](https://user-images.githubusercontent.com/70349967/115404970-0f495d80-a203-11eb-8900-f3e4abc1dcf5.png)

**Comment by echomehran** [comment] 2021-04-20 13:36
> Have you overwritten some styles in your settings.json? I seriously cannot understand what is going on

Yes I have let me show you the pic

**Comment by uloco** [comment] 2021-04-20 13:37
I think that info is just outdated

**Comment by echomehran** [comment] 2021-04-20 13:37
> I think that info is just outdated

maybe, I don't know

**Comment by echomehran** [comment] 2021-04-20 13:38
You mean this, Am I right?
![Screenshot 2021-04-20 180755](https://user-images.githubusercontent.com/70349967/115405703-bcbc7100-a203-11eb-893b-4fa16bc6d1f6.png)

**Comment by uloco** [comment] 2021-04-20 13:41
yes that is why you are seeing the old ui

**Comment by uloco** [comment] 2021-04-20 13:41
remove and restart your editor please

**Comment by echomehran** [comment] 2021-04-20 13:42
> remove and restart your editor please

what do you mean, Uninstall the vscode ?

**Comment by uloco** [comment] 2021-04-20 13:42
remove that line from your settings.json and restart your editor completely

**Comment by echomehran** [comment] 2021-04-20 13:44
> remove that line from your settings.json and restart your editor completely

I just added that according to the info of the extension but I removed it as you said and nothing has changed

**Comment by echomehran** [comment] 2021-04-20 13:45
I removed it, nothing has changed

**Comment by uloco** [comment] 2021-04-20 13:45
Did you override some workbench color customizations in your settings?

**Comment by echomehran** [comment] 2021-04-20 13:47
> Did you override some workbench color customizations in your settings?

Yes I did, but it was after installing your theme and also it's related to the terminal

**Comment by echomehran** [comment] 2021-04-20 13:47
let me double check

**Comment by uloco** [comment] 2021-04-20 13:48
Hmm. I really don't know why you are seeing the old UI. I cannot reproduce this whatever I do. Sorry...

**Comment by echomehran** [comment] 2021-04-20 13:50
> Hmm. I really don't know why you are seeing the old UI. I cannot reproduce this whatever I do. Sorry...

Whatever man thank you so much
I've tried lots of popular themes but yours is really great and it suits my needs

**Comment by uloco** [comment] 2021-04-20 13:51
Thanks, no problem :). But I still really think it is the old UI you are using somehow. Maybe you could try making a clean install of vscode.

**Comment by echomehran** [comment] 2021-04-20 13:53
Yes, I think you're right the problem is with the UI, I have to figure out how to install the new one

**Comment by uloco** [comment] 2021-04-20 14:05
The terminal changes could also affect the output. maybe they used the output terminal color for this in the old ui.

**Comment by echomehran** [comment] 2021-04-20 14:07
let me remove them

**Comment by echomehran** [comment] 2021-04-20 14:08
But why the white edition has no problem?

**Comment by echomehran** [comment] 2021-04-20 14:10
I just commented those out but still the same result

**Comment by echomehran** [comment] 2021-04-20 14:11
How can I install the new UI?

**Comment by echomehran** [comment] 2021-04-20 14:18
Can you just tweak the color customization to make it work?

**Comment by uloco** [comment] 2021-04-20 14:21
i think the white edition is just using a different color that might be the same for the dark theme. I just cannot find out which one is used for the old ui. I don't know how to make the new UI work. I think it is some caching issue. I would remove vscode completely, remove also caches and installed extensions and try again. (maybe also try with insiders if you have the same issue there.)

**Comment by echomehran** [comment] 2021-04-22 16:00
It's OK on the insiders version :) but is there any way to make the stable version behave like this?
![insiders](https://user-images.githubusercontent.com/70349967/115746350-83be0100-a3a9-11eb-9d81-7ca148bb2fb7.png)

**Comment by uloco** [comment] 2021-04-22 16:34
You could try using settings sync to backup your settings etc and remove vscode completely, clear any caches on your system and then reinstall

**Comment by uloco** [comment] 2021-04-26 11:40
I'm closing this, since it isn't an issue of the theme itself. You can still write here and keep me updated when you have found a way to fix your editor issues. Cheers!

**Closed as completed by uloco** 2021-04-26 11:40 UTC
